// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyEiIDHFd5x8c4WrdMw_Jy5WH0lJfDan4',
    appId: '1:48070634633:web:92950abd6909126db7ea58',
    messagingSenderId: '48070634633',
    projectId: 'notes-management-app-5f2a7',
    authDomain: 'notes-management-app-5f2a7.firebaseapp.com',
    storageBucket: 'notes-management-app-5f2a7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmKNx0pdqmJVTECcyayfMSFMFmyH2att0',
    appId: '1:48070634633:android:106434a9cded5adbb7ea58',
    messagingSenderId: '48070634633',
    projectId: 'notes-management-app-5f2a7',
    storageBucket: 'notes-management-app-5f2a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0n_Wlbln0-FPvVj2v-LKEnQnnMhN_5cE',
    appId: '1:48070634633:ios:493be7290fce05a7b7ea58',
    messagingSenderId: '48070634633',
    projectId: 'notes-management-app-5f2a7',
    storageBucket: 'notes-management-app-5f2a7.firebasestorage.app',
    iosBundleId: 'com.example.flutterNoteManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0n_Wlbln0-FPvVj2v-LKEnQnnMhN_5cE',
    appId: '1:48070634633:ios:493be7290fce05a7b7ea58',
    messagingSenderId: '48070634633',
    projectId: 'notes-management-app-5f2a7',
    storageBucket: 'notes-management-app-5f2a7.firebasestorage.app',
    iosBundleId: 'com.example.flutterNoteManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyEiIDHFd5x8c4WrdMw_Jy5WH0lJfDan4',
    appId: '1:48070634633:web:115016fc6c1977b9b7ea58',
    messagingSenderId: '48070634633',
    projectId: 'notes-management-app-5f2a7',
    authDomain: 'notes-management-app-5f2a7.firebaseapp.com',
    storageBucket: 'notes-management-app-5f2a7.firebasestorage.app',
  );
}
